language: node_js
node_js:
  - "4"
  - "5"
  - "6"
after_script: "./node_modules/.bin/codecov"
branches:
  only:
    - master
before_script:
  - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.2.0.tgz -O /tmp/mongodb.tgz
  - tar -xvf /tmp/mongodb.tgz
  - mkdir /tmp/data
  - ${PWD}/mongodb-linux-x86_64-3.2.0/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --port 27017 &> /dev/null &
